# Generated by Django 5.2.1 on 2025-06-12 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camion', '0003_alter_camion_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('poids_vide', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('poids_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('poids_net', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10)),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pesees_camions', to='camion.camion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
