# Generated by Django 5.2.1 on 2025-06-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(error_messages={'unique': 'Ce partenaire est déja enregistrè !'}, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radar', models.CharField(error_messages={'unique': 'Ce radar existe déja !'}, max_length=15, unique=True)),
                ('immatriculation', models.CharField(max_length=20)),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='camions', to='camion.partenaire')),
            ],
        ),
    ]
