# Generated by Django 5.2.1 on 2025-06-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camion', '0002_camion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
